fix uninitialized constant in padrino stop command
calling padrino stop --pid=path/to/pid fails with the error:
NameError: uninitialized constant #<Class:Padrino::Cli::Adapter>::Utils

The adaptor uses the Utils class, but it is not loaded at when using the
padrino binary stop command.

Add require 'padrino-support' to load the Utils class in the apadtor.rb
file.